### ISSUE TITLE
findByIdempotencyKey: return type

### ISSUE THREAD

**Issue by kasium** [VilledeMontreal/express-idempotency#22]
Hey,

The function `findByIdempotencyKey` in `IIdempotencyDataAdapter` has the return type `Promise<IdempotencyResource>`. However, the `InMemoryDataAdapter` returns `null` which doesn't fit. Can you please clarify?

Thanks

**Comment by joscelynjean** [comment]
Hi Kasium,

The function `findByIdempotencyKey` in `InMemoryDataAdapter` can return `null` if it does not found the resource associated with your key. Maybe I could have thrown an exception instead.

It is the same behavior if you choose the use the Mongo adapter found here : 
https://github.com/VilledeMontreal/express-idempotency-mongo-adapter/blob/master/src/adapter.ts

For the next release, I will add to the interface documentation just to clarify the behavior.

Thank you for your comment.

**Comment by kasium** [comment]
@joscelynjean thanks a lot. Can you please also adapt the return type in the interface to `Promise<IdempotencyResource|null>` if you don't choose the exception way?

**Comment by joscelynjean** [comment]
@kasium Thanks for the suggestion. I will check this out.

**Comment by dmmulroy** [comment]
I would also like to to see the type for `findByIdempotencyKey` updated to return `Promise<IdempotencyResource | null>`. Would you welcome a PR updating this?

**Comment by joscelynjean** [comment]
I will prepare for an official release this week. Thank you @dmmulroy

**Comment by joscelynjean** [comment]
Now fixed in version 1.0.5
