### ISSUE TITLE
Response.writeHead never called when client timeout and close the connection

### ISSUE THREAD

**Issue by lawp09** [VilledeMontreal/express-idempotency#26]
When the client timeout occurs and the TCP connection is closed the Nodejs response.writeHead() function is not automatically called. In that case, the writeHeadHook Promise is never resolved and the IdempotencyResponse is never built. We would like to persist the response in the memory and the adapter.

**Comment by joscelynjean** [comment]
I can't remember why I used writeHead to retrieve the status code while it is available in the response.
I will accept the Pull request and deploy a release candidate just to ensure that there is no impact.

**Comment by lawp09** [comment]
Thank you @joscelynjean
